### ISSUE TITLE
Is there a live website for this repo?

### ISSUE THREAD

**Issue by secondl1ght** [pedromvpg/bitcoinforlocalbusiness#16]
I remember seeing a website with this content a while ago but I don't see the link to it in this repo.

**Comment by secondl1ght** [comment]
Awesome thanks!

**Comment by secondl1ght** [comment]
@pedromvpg I put in a PR to add the link to readme if you want to merge. :)

**Comment by pedromvpg** [comment]
Perfection 
Thanks
